<?php

declare(strict_types=1);

namespace App\Jobs;

use App\Models\User\User;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Queue\Queueable;

class CreatePullRequestJob implements ShouldQueue
{
    use Queueable;

    /** Create a new job instance. */
    public function __construct(private User $user) {}

    /** Execute the job. */
    public function handle(): void
    {
        $client = app(GitHubFactory::class)->make([
            'token' => $this->user->github_token,
            'method' => 'token',
        ]);

        $client->api('pull_request')->create('usuario', 'repo', [
            'title' => 'Refactor: upgrade Laravel 9 → 10',
            'head' => 'feature/upgrade-laravel-10',
            'base' => 'main',
            'body' => 'This PR was automatically generated by Rector Cloud 🚀',
        ]);

    }
}
